import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { CustomThemeProvider } from "@/CustomThemeProvider";
import { Toaster } from "sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` antialiased dark:bg-slate-900`}
      >

        <CustomThemeProvider>
          <Navbar />
          {children}
          <Toaster />
        </CustomThemeProvider>

      </body>
    </html>
  );
}
